#!/usr/bin/env bash

filename=''
window_scale=1
print_help=0

for i in "$@"; do
    case "$i" in
        --clean)
            make -C emu clean
            exit $?
            ;;
        --scale)
            echo "ERROR: --scale flag must have an argument." >&2
            exit 1
            ;;
        --scale=*)
            window_scale="${i#*=}"
            ;;
        --help) print_help=1 ;;
        *)
            filename="$i"
            if [ ! -f "$filename" ]; then
                echo "ERROR: no such file '$filename'" >&2
                exit 1
            fi
            ;;
    esac
done

if [ -z "$filename" ] || [ "$print_help" == 1 ]; then
    echo "Usage: [FLAGS] $0 <ino file>" >&2
    echo >&2
    echo "Flags:" >&2
    echo "  --clean         | Remove build files and exit." >&2
    echo "  --scale=[SCALE] | Scale the window by an integer amount." >&2
    echo "  --help          | Display this message." >&2
    echo "To remove build files, run" >&2
    echo "  $0 --clean" >&2
    exit "$([ "$print_help" == 1 ])"
fi



rsync "$1" emu/ino.cpp -u || exit 1
rsync -a src emu/ -u || exit 1
make -C emu WINDOW_SCALE="$window_scale" || exit 1

emu/ino || exit 1
